import Head from "next/head";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "cashcramento",
  description:
    "Generated by cashcramento. This is the most affiliate platform named cashcramento. This is the best CPA Network, top CPA Network in the world.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="google-site-verification"
          content="FJMTDZ53LXva_wOrI8wLy5PgEVpmMnJDcCUUI6zcjd0"
        />
      </Head>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}

// import { Roboto } from "next/font/google";
// import "./globals.css";

// const roboto = Roboto({
//   weight: ["400", "700"],
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "cashcramento",
//   description:
//     "Generated by cashcramento. This is the most affiliate platform named cashcramento. This is the best CPA Network, top CPA Network in the world.",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={roboto.className}>{children}</body>
//     </html>
//   );
// }
