import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "CashCramento",
  description:
    "Generated by CashCramento. This is the most affiliate platform named cashcramento. This is the best CPA Network, top CPA Network in the world named cashcramento.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
